name: Remove label that triggered the CI

on:
  workflow_call:

jobs:
  remove_label:
    if: ${{ inputs.label == 'run_tests' }}

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Remove run_tests label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: run_tests
